# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paperTitle', models.TextField(primary_key=True, serialize=False)),
                ('journalName', models.DateTimeField()),
                ('papaerDate', models.DateField()),
                ('papaerAuthor', models.TextField()),
            ],
        ),
    ]
