# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='journalName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='papaerDate',
            field=models.DateTimeField(),
        ),
    ]
