# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170609_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='uploadedBy',
            field=models.TextField(default='zyc'),
        ),
    ]
