# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_paper_uploadedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='uploadedBy',
            field=models.TextField(),
        ),
    ]
