# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170609_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='uploadedBy',
        ),
    ]
