# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_paper_uploadedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='uploadedBy',
            field=models.TextField(default='123'),
        ),
    ]
