# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170609_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='jobTitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.TextField(),
        ),
    ]
