# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170609_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(),
        ),
    ]
