# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170612_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.TextField(default='123'),
        ),
    ]
